# Generated by Django 5.2.4 on 2025-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り'),
        ),
    ]
